### ISSUE TITLE
art_calibration: Fix Z axis so it goes upwards

### ISSUE THREAD

**Issue by ZdenekM** [robofit/ar-table-itable#53]

**Comment by Kapim** [comment]
fixed by #92

**Comment by ZdenekM** [comment]
Ještě je to potřeba opravit na těchto místech (a otestovat):
- https://github.com/robofit/ar-table-itable/blob/master/art_brain/src/node.py#L509
- https://github.com/robofit/ar-table-itable/blob/master/art_detectors/art_arcode_detector/src/detector.py#L81
- https://github.com/robofit/ar-table-pr2/blob/master/art_table_pointing/src/kinect_node.cpp#L133
- v skeleton trackingu - publikuje se tam user_activity - to dokonce ani nemáme na gitu :(

Je to vše?

**Comment by ZdenekM** [comment]
PR2 se nekalibruje - include launch fajlu pro ni je zakomentovaný: https://github.com/robofit/ar-table-itable/blob/master/art_calibration/launch/art_calibration.launch
