### ISSUE TITLE
Integrate touch foil

### ISSUE THREAD

**Issue by ZdenekM** [robofit/ar-table-itable#59]
**art_touch_driver**
- [x] read singletouch data (python-evdev?) -> publish as PoseStamped (```/art/interface/touchtable/single```)
- [x] calibration (homography from arbitrary number of points) - ask art_projected_gui to show those points (service)
- [x] latched bool topics: ```/art/interface/touchtable/calibrated```, ```/art/interface/touchtable/calibrating```
- [x] normal (not latched) topic: ```/art/interface/touchtable/touch_detected``` (std_msgs/Empty)
- [ ] parameter ```/art/interface/touchtable/active_area``` -> array of x,y coordinates defining touchable area on the table
- [x] empty service ```/art/interface/touchtable/calibrate``` (called by art_brain)
- [x] save calibration on the parameter server

**art_projected_gui**
- [x] service to show calibration points:  ```/art/interface/projected_gui/touch_calibration``` (PointStamped[])
- [x] read ```/art/interface/touchtable/touch_detected``` and display calibrations points (one by one)
- [x] new cursor type
- [x] make pointing/touch cursors work together
- [ ] show active area

**art_brain**
- [x] wait until art_projected_gui is ready, check if touchtable requires calibration (```/art/interface/touchtable/calibrated```) and if so, ask it to calibrate by calling service ```/art/interface/touchtable/calibrate```

**Other stuff**
- [x] test calibration with a new table
- [x] make a cool video ;-)

**Comment by ZdenekM** [comment]
Reading of evdev events: http://python-evdev.readthedocs.io/en/latest/index.html

**Comment by ZdenekM** [comment]
https://github.com/robofit/ar-table-common/blob/master/art_msgs/srv/TouchCalibrationPoints.srv

**Comment by ZdenekM** [comment]
#75 - basic ability to display calibration points in art_projected_gui

**Comment by Kapim** [comment]
#77 - reads events and publish them uncalibrated to `/art/interface/touchtable/single`

**Comment by ZdenekM** [comment]
#84 - calibration. Seems to be working fine with GUI. Maybe there should be some protection against accidental "double touch" of the same point (during calibration).
